switch("define", "INTERVALS_API_KEY=REDEFINE")
switch("define", "INTERVALS_ATHLETE=REDEFINE")
switch("define", "SHEET_ID=REDEFINE")
switch("define", "CLIENT_ID=REDEFINE")
switch("define", "CLIENT_SECRET=REDEFINE")
switch("define", "REFRESH_TOKEN=REDEFINE")
